services:
  quarkus:
    image: ibm/teste:1.0.0-SNAPSHOT
    environment:
      - GREETING_MESSAGE
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  prom-config: {}